import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://qaplayground.com/bank');
  await page.getByTestId('username-input').click();
  await page.getByTestId('username-input').fill('n');
  await page.getByTestId('username-input').click();
  await page.getByTestId('username-input').fill('admin');
  await page.getByTestId('password-input').click();
  await page.getByTestId('password-input').click();
  await page.getByTestId('password-input').fill('admin123');
  await page.getByTestId('login-button').click();
  await page.getByTestId('password-input').dblclick();
  await page.getByTestId('password-input').click();
  await page.getByTestId('password-input').fill('admin123');
  await page.getByTestId('login-button').click();
  await page.getByTestId('login-button').click();
  await page.getByTestId('login-button').click();
  await page.getByTestId('password-input').dblclick();
  await page.getByTestId('password-input').fill('admin123');
  await page.getByTestId('login-button').click();
  await page.getByTestId('username-input').dblclick();
  await page.getByTestId('username-input').click();
  await page.getByTestId('username-input').fill('admin');
  await page.getByTestId('login-button').click();
  await page.getByTestId('quick-add-account').click();
  await page.getByTestId('account-name-input').fill('akhil');
  await page.getByTestId('account-type-select').click();
  await page.getByLabel('Savings Account').getByText('Savings Account').click();
  await page.getByTestId('initial-balance-input').click();
  await page.getByTestId('initial-balance-input').fill('5000');
  await page.getByTestId('save-account-button').click();
  await page.getByTestId('edit-account-id_1779294945687_kxejfnqra').click();
  await page.getByTestId('account-name-input').fill('nikil');
  await page.getByTestId('account-type-select').click();
  await page.getByLabel('Checking Account', { exact: true }).getByText('Checking Account').click();
  await page.getByTestId('save-account-button').click();
  await page.getByTestId('delete-account-id_1779294945687_kxejfnqra').click();
  await page.getByTestId('confirm-delete-button').click();
});